# Generated by Django 5.0.3 on 2024-04-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_linkdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='linkData',
            new_name='Data',
        ),
    ]
