# Generated by Django 5.0.3 on 2024-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_rename_linkdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=10000),
        ),
    ]
