# Generated by Django 5.0.3 on 2024-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_alter_data_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='text',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
