# Generated by Django 5.0.6 on 2024-06-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment", "0006_delete_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="pos",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
