# Generated by Django 5.0.6 on 2024-06-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment", "0007_link_pos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="pos",
        ),
    ]
